### PR TITLE
Replace special characters in the generated branch name

### LINKED ISSUE #58: Replace special characters in the branch names generated by the script
Currently the script can generate branch names that don't match the desired format, so the push could fail.

### PR DESCRIPTION
**Pull request by antalasztrik**
Closes #58

### CODE REVIEW

**Comment by antalasztrik** [comment]
Oops, looks like my VSCode decided to format the JS text for me. Do we stick with the "no space after function name" style for now or should I refactor this?

File: scripts/lib/branch.js [hunk 1]
```diff
@@ -19,6 +19,9 @@ async function branchNameForIssue (owner, repository, issueNumber, index) {
   const namePart = i.title
     .toLowerCase()
     .replace(/ /g, '-')
+    .replace(/:/g, '-')
+    .replace(/,/g, '-')
+    .replace(/\//g, '-')
```
Comment (battila7) [inline scripts/lib/branch.js]: Although, this one is great, you may achieve the same using a single regexp. Or is there any particular reason you decided to go with multiple `replace` calls instead of a single regexp?

**Review by battila7 — CHANGES_REQUESTED** [review]

File: scripts/lib/branch.js (hunk 1 above)
Comment (antalasztrik) [reply scripts/lib/branch.js]: Well the only reason I did it this way, is because I don't really like writing/reading regexps. Should I rewrite it?

Comment (battila7) [reply scripts/lib/branch.js]: A classic quote in the topic:

> Some people, when confronted with a problem, think "I know, I'll use regular expressions." Now they have two problems.

https://blog.codinghorror.com/regular-expressions-now-you-have-two-problems/

A great tool that can help a lot working with regular expressions is https://regexr.com/

Comment (antalasztrik) [reply scripts/lib/branch.js]: To be fair, this was not a "difficult" regex to add (hope I got it right), so now it's replaced.

**Comment by battila7** [comment]
> 
> 
> Oops, looks like my VSCode decided to format the JS text for me. Do we stick with the "no space after function name" style for now or should I refactor this?

@antalasztrik A `pnpm run lint:javascript:fix` will solve this :)

File: scripts/lib/branch.js (hunk 1 above)
Comment (battila7) [reply scripts/lib/branch.js]: Checked it, it's on point 👍 Thanks for the rewrite!

**Review by battila7 — CHANGES_REQUESTED** [review]
🔥

**Review by battila7 — APPROVED** [review]
I mean, approve 😄
